language: python
python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
env:
  - TOX_ENV=py
  - TOX_ENV=static_check
install: pip install tox
script: tox -e $TOX_ENV
deploy:
  provider: pypi
  user: mavlyutov
  distributions: "sdist bdist_wheel"
  password:
    secure: Aimu/wB30KsebRDHFLJdo5M6AsrKfhl6dL5wrdbFMeyklx6us18Rg6KD+KagjrHwVzxMifi2O/ael7YKSXN6nGXFo0VQCG3CNPYCnRvgLqh1IFTMvmVpWn3R4J7oi+UKc40Ipeaq+3yuZo+ssESXpjQIwIBMxifSA78Q3hqmgWA=
  on:
    tags: true
    branch: master
